# Render Blueprint for WingIt Social Media Platform
# This file defines all services for deployment

services:
  # Frontend Service (Next.js)
  - type: web
    name: wingit-frontend
    env: node
    rootDir: fe
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://wingit-backend-s1gb.onrender.com
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://wingit-backend-s1gb.onrender.com
      - key: NEXT_PUBLIC_WEBSOCKET_URL
        value: wss://wingit-backend-s1gb.onrender.com/ws
      - key: NEXT_PUBLIC_AI_URL
        value: http://YOUR_LOCAL_IP:5000
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    
  # Backend Service (Spring Boot) - Deploy this manually after Blueprint
  # Java is not supported in Render Blueprints, deploy separately
  
  # NOTE: AI Server runs locally due to RAM limitations on Render free tier
  # Make sure to:
  # 1. Run AI server locally: docker-compose up --build (in AI directory)
  # 2. Update YOUR_LOCAL_IP in environment variables
  # 3. Ensure your local machine is accessible from Render (public IP/ngrok)
    healthCheckPath: /health

# Database
databases:
  - name: wingit-db
    databaseName: wingit
    user: wingit_user
    plan: free # Free PostgreSQL database
