# Render Blueprint for WingIt Social Media Platform
# This file defines all services for deployment

services:
  # Frontend Service (Next.js)
  - type: web
    name: wingit-frontend
    env: node
    rootDir: fe
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://wingit-backend.onrender.com
      - key: NEXT_PUBLIC_WEBSOCKET_URL
        value: wss://wingit-backend.onrender.com/ws
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    
  # Backend Service (Spring Boot)
  - type: web
    name: wingit-backend
    env: java
    rootDir: server
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/server-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wingit-db
          property: connectionString
      - key: DB_DRIVER
        value: org.postgresql.Driver
      - key: JWT_SECRET
        generateValue: true
      - key: PROFANITY_DETECTION_URL
        value: https://wingit-ai.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false # Set manually in Render dashboard
      - key: GOOGLE_CLIENT_SECRET
        sync: false # Set manually in Render dashboard
      - key: CLOUDINARY_CLOUD_NAME
        sync: false # Set manually in Render dashboard
      - key: CLOUDINARY_API_KEY
        sync: false # Set manually in Render dashboard
      - key: CLOUDINARY_API_SECRET
        sync: false # Set manually in Render dashboard
      - key: EMAIL_USERNAME
        sync: false # Set manually in Render dashboard
      - key: EMAIL_PASSWORD
        sync: false # Set manually in Render dashboard
      - key: SPRING_PROFILES_ACTIVE
        value: production
    healthCheckPath: /api/v1/health
    
  # AI Server Service (Python Flask)
  - type: web
    name: wingit-ai
    env: python
    rootDir: AI
    buildCommand: pip install -r requirements_deploy.txt
    startCommand: python real_ai_server.py
    envVars:
      - key: MODEL_PATH
        value: ./best_phobert_model.pth
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /health

# Database
databases:
  - name: wingit-db
    databaseName: wingit
    user: wingit_user
    plan: free # Free PostgreSQL database
