# Render Blueprint for WingIt Social Media Platform
# This file defines all services for deployment

services:
  # Frontend Service (Next.js)
  - type: web
    name: wingit-frontend
    env: node
    rootDir: fe
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://wingit-backend-s1gb.onrender.com
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://wingit-backend-s1gb.onrender.com
      - key: NEXT_PUBLIC_WEBSOCKET_URL
        value: wss://wingit-backend-s1gb.onrender.com/ws
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    
  # Backend Service (Spring Boot) - Deploy this manually after Blueprint
  # Java is not supported in Render Blueprints, deploy separately
  # AI Server Service (Python Flask)
  - type: web
    name: wingit-ai
    env: python
    rootDir: AI
    buildCommand: pip install -r requirements_deploy.txt
    startCommand: python real_ai_server.py
    envVars:
      - key: MODEL_PATH
        value: ./best_phobert_model.pth
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /health

# Database
databases:
  - name: wingit-db
    databaseName: wingit
    user: wingit_user
    plan: free # Free PostgreSQL database
